services:
  db:
    image: postgres:15
    container_name: material_todo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: material_todo_go
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: material_todo_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: material_todo_go
      DB_PORT: 5432
    ports:
      - "2525:2525"

volumes:
  pgdata:
